- name: Deploy Ticket Booking App
  hosts: webserver
  become: yes

  vars:
    backend_port: 5000
    frontend_port: 3000


  tasks:

    - name: Pull backend image
      docker_image:
        name: ranvidu1130/ticket-booking-backend
        tag: latest
        source: pull

    - name: Run backend container
      docker_container:
        name: backend
        image: ranvidu1130/ticket-booking-backend:latest
        state: started
        restart_policy: always
        networks:
          - name: app_network
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        env:
          DB_HOST: mysql
          DB_USER: "{{ db_user }}"
          DB_PASSWORD: "{{ db_password }}"
          DB_NAME: "{{ db_name }}"

    - name: Pull frontend image
      docker_image:
        name: ranvidu1130/ticket-booking-frontend
        tag: latest
        source: pull

    - name: Run frontend container
      docker_container:
        name: frontend
        image: ranvidu1130/ticket-booking-frontend:latest
        state: started
        restart_policy: always
        networks:
          - name: app_network
        ports:
          - "{{ frontend_port }}:5173"
        env:
          VITE_BACKEND_URL: "http://{{ ansible_host }}:{{ backend_port }}"
